name: publish sample image to ghcr

on: [push]

permissions:
    contents: read
    packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build and push
          run: |
            docker build . -t ghcr.io/tjnangosha/hello-world:latest
            docker push ghcr.io/tjnangosha/hello-world:latest