name: publish sample image to ghcr

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        run: |
          docker build . -t ghcr.io/${{ github.repository }}/hello-world:latest
          docker push ghcr.io/${{ github.repository }}/hello-world:latest